version: '3.7'
services:
  web:
    image: nginx:1.17.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - webapp
  webapp:
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_URI=mongodb://db:27017/my-heroes
      - NODE_ENV=production
  db:
    image: mongo:3.4.16-jessie
    restart: always
    volumes:
      - /data/db:/data/db